### PR TITLE
fix(UI): correct colors of modal buttons

### LINKED ISSUE #1148: colors of 'change' & 'close' buttons at change-role modal should be opposite
### Describe the bug:
Currently 'close' button has a blue and 'change' is gray
image
 I think it will be better to change colors to be opposite:
'close' -grey and 'change' is blue
May be even better to have 'green' color for 'change' button... 
### Tell us about your browser and operating system:
- Browser(s) name and version: 
- Operating System:

### PR DESCRIPTION
**Pull request by shootermv**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

Closes #1148

### CODE REVIEW

File: client/src/modules/dashboard/shared/components/RoleChangeModal.tsx [hunk 1]
```diff
@@ -43,7 +43,7 @@ export const RoleChangeModal: React.FC<{
     <Modal
       modalProps={modalProps}
       title={title}
-      buttons={<Button type="submit">Change</Button>}
+      buttons={<Button type="submit" colorScheme="green">Change</Button>}
```
Comment (gikf) [inline client/src/modules/dashboard/shared/components/RoleChangeModal.tsx:46]:
```suggestion
      formButtonText="Change"
```
This will use the default green button from `Modal`.

File: client/src/components/Modal.tsx [hunk 2]
```diff
@@ -63,7 +63,7 @@ export const Modal = (props: ModalProps) => {
           <ModalFooter>
             {buttonsLeft}
             <HStack>
-              <Button colorScheme="blue" onClick={modalProps.onClose}>
+              <Button onClick={modalProps.onClose}>
```
Comment (gikf) [inline client/src/components/Modal.tsx:66]:
```suggestion
              <Button colorScheme="blue" onClick={modalProps.onClose}>
```
And this doesn't need to be changed in such case.

**Review by gikf — COMMENTED** [review]
Small suggestion, per comment in the issue.

File: client/src/components/Modal.tsx (hunk 2 above)
Comment (shootermv) [reply client/src/components/Modal.tsx:66]: you mean - close button, should stay blue, right?

Comment (gikf) [reply client/src/components/Modal.tsx:66]: Yeah, with green _Change_ that still makes it stand out.

**Review by gikf — APPROVED** [review]
Looks good to me :+1:

**Comment by gikf** [comment]
@all-contributors please add @shootermv for code
