### PR TITLE
fix: loadingUser stuck on error

### LINKED ISSUE #2259: loadingUser doesn't change on error
### Describe the bug:
When `useMeQuery` in `client/src/modules/auth/user.tsx` errors, the `loadingUser` is not changed.

This makes possible to be stuck in loading when there's some error during the query.

I'm not entirely sure what's the appropriate action in such case. The _simple_ thing that comes to mind is just adding error case to the useEffect:
```
    if (error) {
      setData({ loadingUser: false, isLoggedIn: false });
    }
```

### PR DESCRIPTION
**Pull request by gikf**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

Closes #2259

---

- Changes `loadingUser` to `false` when there's `useMeQuery` error.
- Catches errors when creating or destroying session.
- `logout()` along setting `loadingUser` on error is a hacky try to start next time from as clean state as possible. For development that's flipping the `isAuthenticated`.

### CODE REVIEW

File: client/src/hooks/useSession.ts [hunk 1]
```diff
@@ -40,13 +40,16 @@ export const useSession = () => {
   // isAuthenticated does not change immediately after login/logout, so we
   // need to track the intent to prevent accidental session creation/deletion
   const [toLogout, setToLogout] = useState(false);
+  const [error, setError] = useState<Error | undefined>(undefined);
```
Comment (ojeytonwilliams) [inline client/src/hooks/useSession.ts:43]:
```suggestion
  const [error, setError] = useState<Error | null>(null);
```
Bit nicer, imo.

File: client/src/hooks/useSession.ts [hunk 2]
```diff
@@ -40,13 +40,16 @@ export const useSession = () => {
...
 
   const login = async () => {
+    setError(undefined);
```
Comment (ojeytonwilliams) [inline client/src/hooks/useSession.ts:46]:
```suggestion
    setError(null);
```

File: client/src/hooks/useSession.ts [hunk 3]
```diff
@@ -40,13 +40,16 @@ export const useSession = () => {
...
     await loginAuth();
     setCanAlterSession(true);
     setToLogout(false);
   };
   const logout = async () => {
+    setError(undefined);
```
Comment (ojeytonwilliams) [inline client/src/hooks/useSession.ts:52]:
```suggestion
    setError(null);
```

File: client/src/hooks/useSession.ts [hunk 4]
```diff
@@ -59,11 +62,14 @@ export const useSession = () => {
     if (toLogout) {
       destroySession()
         .then(() => refetch())
-        .then(() => apollo.resetStore());
+        .then(() => apollo.resetStore())
+        .catch((e) => setError(e));
```
Comment (ojeytonwilliams) [inline client/src/hooks/useSession.ts:66]: The weird thing about `fetch` is that it doesn't throw errors if there are issues with the request. That means even if we get a status 500 from the server, we don't get to the catch.  You can easily test this by calling `next('message')` in the `/login` middleware.

To have something to catch, you can simply throw an error inside create/destroySession if `ok` is falsy. You _could_ handle it it with a conditional in the `then`, but catching seems fine here!

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]

File: client/src/hooks/useSession.ts (hunk 4 above)
Comment (gikf) [reply client/src/hooks/useSession.ts:66]: This is interesting. I generally was putting a hammer on server, by deleting some line in `app.ts` so it would error after another compilation. For that case `fetch` is indeed throwing.

Comment (ojeytonwilliams) [reply client/src/hooks/useSession.ts:66]: You may be seeing something different, but for what it's worth I was confused by the network errors appearing in the logs. They're not JS errors, they just register that something went wrong during a network request. If they go away when you check "Hide network" in the browser's dev console, we're talking about the same thing.

To the best of my knowledge, you can't catch those errors. However, if you're able to create JS errors by messing with the server, that's really interesting. At least to me, because I'll have learned a thing!

Comment (gikf) [reply client/src/hooks/useSession.ts:69]: Try these steps to reproduce:
- Remove `catch` chained to `destroySession()` and `createSession()`.
- While having running server, change something in `/server/src/app.ts` to make it not compile anymore. For example remove line with `const PORT = process.env.PORT || 5000;`
- Now when pressing _Login_ or _Logout_ there will be unhandled error, from the `fetch`.

Comment (ojeytonwilliams) [reply client/src/hooks/useSession.ts:69]: Thanks for the quick steps to reproduce, it does indeed error in that case! I did a little digging and it turns out that's just how it works: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API#differences_from_jquery

Bit strange, but your code handles both cases, so I think we're good.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:
