### PR TITLE
fix(ui): Add padding to user welcome message

### LINKED ISSUE #1884: Welcoming the user message is cramped and need some spacing
### Describe the bug:

The welcoming message when someone logs in is cramped, it can use some spacing to look better. 

The current looks

image

The desired looks 

image

You can change the file here

https://github.com/freeCodeCamp/chapter/blob/de6fd0842b211ce2be4b3a2d351d7d8e9f86f68f/client/src/modules/home/index.tsx

---

---

To get set up locally, take a look at our [contribution docs](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md). And, if you'd like to discuss more, you can head on over to [Discord](https://discord.gg/QbQd7BpaaH) and say hi, or comment here if you prefer.

### PR DESCRIPTION
**Pull request by nwernink**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

Closes #1884 

This change adds padding to the top of welcome message when a user logins to the platform. Before, the welcome message did not have much separation between it and the header, so by adding more space the welcome message no longer looks cramped to the top.

How it looked before the change:
201352290-352c650b-bad9-4d71-a3b9-b82ef360a09d

How it looks after the change:
Screen Shot 2022-12-04 at 1 58 19 PM

### CODE REVIEW

File: client/src/modules/home/index.tsx [hunk 1]
```diff
@@ -22,7 +22,11 @@ type User = NonNullable<AuthContextType['user']>;
 
 const Welcome = ({ user }: { user: User }) => {
   return (
-    <Flex alignItems={'center'} justifyContent="space-between">
+    <Flex
+      alignItems={'center'}
+      justifyContent="space-between"
+      paddingTop="20px"
+    >
```
Comment (Sboonny) [inline client/src/modules/home/index.tsx:29]: This is way better looking, thank you.

There is an issue with using padding, as it add spacing that latters can use, so languages like Japanese may have issues with weird flow with extra paddings

```suggestion
      marginTop="20px"
```

File: client/src/modules/home/index.tsx [hunk 2]
```diff
@@ -22,7 +22,11 @@ type User = NonNullable<AuthContextType['user']>;
 
 const Welcome = ({ user }: { user: User }) => {
   return (
-    <Flex alignItems={'center'} justifyContent="space-between">
+    <Flex
+      alignItems={'center'}
+      justifyContent="space-between"
+      paddingTop="20px"
```
Comment (Sboonny) [inline client/src/modules/home/index.tsx:28]: I have selected the wrong line 😅

```suggestion 
      marginTop="20px"
```

**Comment by nwernink** [comment]
@Sboonny that makes sense, I am also going to make the same change to the generic welcome message before a user logins because it is currently also cramped as seen below.
Screen Shot 2022-12-05 at 10 21 59 AM

**Comment by Sboonny** [comment]
Go for it 👍

**Review by Sboonny — APPROVED** [review]
#### :sparkles: :tada: **AWESOME!** :tada: :sparkles:

 Hi @nwernink, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.

 Cheers & happy contributing!

**Comment by Sboonny** [comment]
@allcontributors add @nwernink for code
