### PR TITLE
fix: send event creation notification message

### LINKED ISSUE #275: UI: As a future participant after the event, I will automatically get emails notifying me of subsequent events.
Depends on #107

### PR DESCRIPTION
**Pull request by Sboonny**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

Closes #275

<s>I can't test, the variables and how does the email looks. but it shouldn't break anything</s>

### CODE REVIEW

File: server/src/controllers/Events/resolver.ts [hunk 1]
```diff
@@ -807,21 +807,41 @@ ${venueDetails}`;
...
+    }<br />
+    <br />
+    When: ${event.start_at} to ${event.ends_at}
+    <br />
+   ${event.venue ? `Where: ${event.venue.name}.<br />` : ''}
+   ${event.streaming_url ? `Streaming URL: ${event.streaming_url}<br />` : ''}
+   <br />
+    View All of Upcoming Events for ${
+      event.chapter.name
+    }: <a href='https://chapter.freecodecamp.dev/chapters/${
```
Comment (Sboonny) [inline server/src/controllers/Events/resolver.ts:821]: Should update this to instanse domain

**Comment by Sboonny** [comment]
@allella The email received look like this 

image

```md
New Upcoming Event for Schimmel, Baumbach and Fadel

When: Wed Sep 07 2022 15:28:59 GMT+0000 (Coordinated Universal Time) to Wed Sep 07 2022 15:28:59 GMT+0000 (Coordinated Universal Time)
Where: Kuhlman LLC.

View All of Upcoming Events for Schimmel, Baumbach and Fadel: [Schimmel, Baumbach and Fadel chapter.](https://chapter.freecodecamp.dev/chapters/1)
RSVP or Learn More https://3000-sboonny-chapter-22otcl39z5p.ws-eu63.gitpod.io/events/16?emaillink=true.
-----------------------

Event Details:

- Stop receiving upcoming event notifications for Schimmel, Baumbach and Fadel. you can do it here: https://3000-sboonny-chapter-22otcl39z5p.ws-eu63.gitpod.io/events/16?emaillink=true.
- More about Schimmel, Baumbach and Fadel or to unfollow this chapter: https://3000-sboonny-chapter-22otcl39z5p.ws-eu63.gitpod.io/chapters/1.

----------------------------
You received this email because you follow this Schimmel, Baumbach and Fadel chapter.

See the options above to change your notifications.
Unsubscribe Options
- [Attend this event, but only turn off future notifications for this event](https://3000-sboonny-chapter-22otcl39z5p.ws-eu63.gitpod.io/unsubscribe?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiZXZlbnQiLCJpZCI6MTYsInVzZXJJZCI6MTAsImlhdCI6MTY2MjU2NDYyOH0.If8GFUTUXk1_jkxKrE3BEgH6D2wUSETar4bqclFY9Oc)
- Or, [stop receiving all notifications by unfollowing chapter](https://3000-sboonny-chapter-22otcl39z5p.ws-eu63.gitpod.io/unsubscribe?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiY2hhcHRlciIsImlkIjoxLCJ1c2VySWQiOjEwLCJpYXQiOjE2NjI1NjQ2Mjh9._XndSVGb85RuZ8sqVVSMCwneeDoG4zqa4isWetPmQno)
```

Is there something I have missed?

File: server/src/controllers/Events/resolver.ts [hunk 2]
```diff
@@ -807,21 +807,39 @@ ${venueDetails}`;
...
-    ----------------------------<br>
-    You received this email because you follow this chapter.<br>
-    <br>
-    See the options above to change your notifications.`;
+    } or to unfollow this chapter: <a href="${chapterURL}">${chapterURL}</a>.<br />
+    <br />
+    ----------------------------<br />
+    You received this email because you follow this ${
+      event.chapter.name
+    } chapter.<br />
```
Comment (gikf) [inline server/src/controllers/Events/resolver.ts:837]:
```suggestion
    You received this email because you follow ${
      event.chapter.name
    } chapter.<br />
```

File: server/src/controllers/Events/resolver.ts [hunk 3]
```diff
@@ -807,21 +807,39 @@ ${venueDetails}`;
...
+   ${event.venue ? `Where: ${event.venue.name}.<br />` : ''}
+   ${event.streaming_url ? `Streaming URL: ${event.streaming_url}<br />` : ''}
+   <br />
+    View All of Upcoming Events for ${
+      event.chapter.name
+    }: <a href='${chapterURL}'>${event.chapter.name} chapter.</a><br />
+    RSVP or Learn More <a href="${eventURL}">${eventURL}</a>.<br />
+    -----------------------<br />
+    <br />
+    Event Details: <br />
```
Comment (gikf) [inline server/src/controllers/Events/resolver.ts:825]: This seems to be in the wrong place (if it's needed at all), details of the event are above of it.

**Comment by Sboonny** [comment]
the new version 

```md
New Upcoming Event for Fadel and Sons.

When: Wed Sep 07 2022 17:52:43 GMT+0000 (Coordinated Universal Time) to Wed Sep 07 2022 17:52:43 GMT+0000 (Coordinated Universal Time)
Where: Fisher - Beer.

View All of Upcoming Events for Fadel and Sons: [Fadel and Sons chapter](https://3000-sboonny-chapter-f886dldyyl1.ws-eu63.gitpod.io/chapters/1).
RSVP or Learn More https://3000-sboonny-chapter-f886dldyyl1.ws-eu63.gitpod.io/events/16?emaillink=true.
----------------------------

- Stop receiving upcoming event notifications for Fadel and Sons. you can do it here: https://3000-sboonny-chapter-f886dldyyl1.ws-eu63.gitpod.io/events/16?emaillink=true.
- More about Fadel and Sons or to unfollow this chapter: https://3000-sboonny-chapter-f886dldyyl1.ws-eu63.gitpod.io/chapters/1.

----------------------------
You received this email because you follow Fadel and Sons chapter.

See the options above to change your notifications.
Unsubscribe Options
- [Attend this event, but only turn off future notifications for this event](https://3000-sboonny-chapter-f886dldyyl1.ws-eu63.gitpod.io/unsubscribe?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiZXZlbnQiLCJpZCI6MTYsInVzZXJJZCI6MTQsImlhdCI6MTY2MjU3MzE4OH0.SI7xVhomIsgireWxmOZd7jtf0nJSXkT68IcfPwH7dbY)
- Or, [stop receiving all notifications by unfollowing chapter](https://3000-sboonny-chapter-f886dldyyl1.ws-eu63.gitpod.io/unsubscribe?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiY2hhcHRlciIsImlkIjoxLCJ1c2VySWQiOjE0LCJpYXQiOjE2NjI1NzMxODh9.ff_LZCFjtGM3oPW1EWeRM_S1RZK3_O-DcRFye8N7NVQ)
```

image

File: server/src/controllers/Events/resolver.ts [hunk 4]
```diff
@@ -807,20 +807,35 @@ ${venueDetails}`;
...
+   <br />
+    View All of Upcoming Events for ${
+      event.chapter.name
+    }: <a href='${chapterURL}'>${event.chapter.name} chapter</a>.<br />
+    RSVP or Learn More <a href="${eventURL}">${eventURL}</a>.<br />
+    ----------------------------<br />
+    <br />
+    - Stop receiving upcoming event notifications for ${
+      event.chapter.name
+    }. you can do it here: <a href="${eventURL}">${eventURL}</a>.<br />
```
Comment (Sboonny) [inline server/src/controllers/Events/resolver.ts:827]:
```suggestion
}. You can do it here: <a href="${eventURL}">${eventURL}</a>.<br />
```

File: server/src/controllers/Events/resolver.ts [hunk 5]
```diff
@@ -822,9 +822,12 @@ ${venueDetails}`;
     RSVP or Learn More <a href="${eventURL}">${eventURL}</a>.<br />
     ----------------------------<br />
     <br />
+    About the event: <br />
+    ${event.description}<br />
+    <br />
     - Stop receiving upcoming event notifications for ${
       event.chapter.name
-    }. You can do it here: <a href="${eventURL}">${eventURL}</a>.<br />
+    }. You can do it here: <a href="${chapterURL}">${chapterURL}</a>.<br />
```
Comment (Sboonny) [inline server/src/controllers/Events/resolver.ts:830]:
```suggestion
    }. You can do it here: <a href="${eventURL}">${eventURL}</a>.<br />

**Review by ojeytonwilliams — APPROVED** [review]
Nice job, this is much better!
