### PR TITLE
fix: correct colors of buttons at sendEmailModal

### LINKED ISSUE #1370: send email to attendees modal button colors is incorrect
### Describe the bug:
 currently 'close' button has 'primary' color, and 'send' is gray. i think it better if colors will be opposite

image

### Tell us about your browser and operating system:
- Browser(s) name and version: 
- Operating System:

### PR DESCRIPTION
**Pull request by shootermv**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

Closes #1370

### CODE REVIEW

File: client/src/modules/dashboard/Events/components/SendEmailModal.tsx [hunk 1]
```diff
@@ -99,10 +99,15 @@ const SendEmailModal: React.FC<SendEmailModalProps> = ({
...
 
         <ModalFooter>
-          <Button colorScheme="teal" mr={3} onClick={onClose}>
+          <Button mr={3} onClick={onClose}>
             Close
           </Button>
-          <Button type="submit" variant="solid" form="sendemail">
+          <Button
+            type="submit"
+            colorScheme={'green'}
```
Comment (Sboonny) [inline client/src/modules/dashboard/Events/components/SendEmailModal.tsx:107]:
```suggestion
            colorScheme={'accent'}
```

**Review by Sboonny — CHANGES_REQUESTED** [review]
We can change it to a theme, because with it coming along we need to account for dark mode as well. https://chakra-ui.com/docs/styled-system/css-variables

File: client/src/modules/dashboard/Events/components/SendEmailModal.tsx (hunk 1 above)
Comment (Sboonny) [reply client/src/modules/dashboard/Events/components/SendEmailModal.tsx:107]: you don't have to create a theme, just change it and I will create a quick pull request with colors themes for style guide, too

**Review by Sboonny — APPROVED** [review]
LGTM 🎉, thank you for your contribution to the page! 👍.

I will merge it, later when merge file is merged
