### PR TITLE
fix: form validations

### LINKED ISSUE #2228: Required fields in form are not forced
### Describe the bug:
I just noticed the fields that are supposed to be required in forms, and be validated in client, do not really force that requirement.

Tested locally and on gitpod.

### PR DESCRIPTION
**Pull request by atosh502**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

Closes #2228

Updated Forms: 

- [x] EventForm.tsx - [client/src/modules/dashboard/Events/components/EventForm.tsx](https://github.com/freeCodeCamp/chapter/blob/main/client/src/modules/dashboard/Events/components/EventForm.tsx)
- [x] ChapterForm.tsx - [client/src/modules/dashboard/Chapters/components/ChapterForm.tsx](https://github.com/freeCodeCamp/chapter/blob/main/client/src/modules/dashboard/Chapters/components/ChapterForm.tsx)
- [x] VenueForm.tsx - [client/src/modules/dashboard/Venues/components/VenueForm.tsx](https://github.com/freeCodeCamp/chapter/blob/main/client/src/modules/dashboard/Venues/components/VenueForm.tsx) 

Changes made: 

1. Add the required validation while registering the chakra input with `react-hook-form`. Chakra's [`isRequired`](https://chakra-ui.com/docs/components/form-control/usage#making-a-field-required) only adds the red asterisk. 
2. Use the error from `RHF`'s form state to make the [input field invalid](https://chakra-ui.com/docs/components/form-control/props#props). 
```jsx
  const {
      handleSubmit,
      register,
      formState: { isDirty, errors },
    } = useForm<CreateChapterInputs>({
      defaultValues,
    });
  
  const error = errors[key]?.message;
  
  <Component
      ...
      error={error}
      {...register(key, {
        required: {
          value: required,
          message: `${label} is required`,
        },
      })}
    />
```

### CODE REVIEW

File: client/src/modules/dashboard/Venues/components/VenueForm.tsx [hunk 1]
```diff
@@ -175,19 +175,21 @@ const VenueForm: React.FC<VenueFormProps> = (props) => {
...
+            {...register(key)}
+            type={type}
+            isRequired={isRequired}
+            step={step}
+            max={max}
+            min={min}
+            isDisabled={loading}
+          />
+        );
+      })}
```
Comment (gikf) [inline client/src/modules/dashboard/Venues/components/VenueForm.tsx:192]: Just a nitpick, could you revert change in this file? The other changes that were made alongside in here were reverted.

Comment (atosh502) [reply client/src/modules/dashboard/Venues/components/VenueForm.tsx]: Done

**Review by gikf — APPROVED** [review]
Looks good :+1:
