### PR TITLE
fix: sponsor fields should not be empty

### LINKED ISSUE #846: Default sponsor fields should not be empty
As an event organiser that's creating a new event, if I keep adding new sponsors they should not be empty

image
The above should never happen. 

Since each sponsor can only be added once, each new sponsor should be of a type that has un-selected sponsors.  When all sponsors have been added, the Add button should be disabled.

For example:

- If there is a single sponsor of the FOOD type, then the first sponsor added should be that and the button should immediately be disabled.

### PR DESCRIPTION
**Pull request by gikf**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

Still required:
- [x] Clean up

Closes #846

---

- Disables `Add` button, when all existing sponsors are added.
- When adding new sponsor, default sponsor type and sponsor are selected from still available sponsors.
- Available sponsor types and sponsors are limited based on selections in other fields.
- Moves default sponsor types to utils.
- Moves functions getting allowed sponsors, sponsor types to utils.
- Any notes are appreciated.
- Tested on local fork.

### CODE REVIEW

File: client/src/modules/dashboard/Events/components/EventFormUtils.ts [hunk 1]
```diff
@@ -161,3 +161,83 @@ export const formatValue = (field: Field, store?: IEventData): any => {
...
+  sponsorFieldId: number,
+) =>
+  sponsorTypes.filter(({ type }) =>
+    hasTypeAllowedSponsors(
+      sponsorData,
+      type,
+      watchSponsorsArray,
+      sponsorFieldId,
+    ),
+  ) ?? [];
```
Comment (ojeytonwilliams) [inline client/src/modules/dashboard/Events/components/EventFormUtils.ts:178]:
```suggestion
  sponsorTypes.filter(
    ({ type }) =>
      getAllowedSponsorsForType(
        sponsorData,
        type,
        watchSponsorsArray,
        sponsorFieldId,
      ).length,
  );
```
It feels like overkill to create an extra function when `.length` does the same job.

File: client/src/modules/dashboard/Events/components/EventFormUtils.ts [hunk 2]
```diff
@@ -161,3 +161,83 @@ export const formatValue = (field: Field, store?: IEventData): any => {
...
+
+export const getAllowedSponsorsForType = (
+  sponsorData: SponsorsQuery,
+  sponsorType: string,
+  watchSponsorsArray: EventSponsorInput[],
+  sponsorFieldId?: number,
+) =>
+  sponsorData.sponsors.filter(
+    (sponsor) =>
+      hasMatchingSponsorType(sponsor, sponsorType) &&
```
Comment (ojeytonwilliams) [inline client/src/modules/dashboard/Events/components/EventFormUtils.ts:188]:
```suggestion
      sponsor.type === sponsorType &&
```
I don't think we need any abstraction here. We only use `hasMatchingSponsorType` here and it's easy enough to understand.

File: client/src/modules/dashboard/Events/components/EventFormUtils.ts [hunk 3]
```diff
@@ -161,3 +161,83 @@ export const formatValue = (field: Field, store?: IEventData): any => {
...
+) =>
+  watchSponsorsArray.findIndex(
+    (selectedSponsor) => selectedSponsor.id === sponsor.id,
+  );
+
+const hasMatchingSponsorType = (
+  sponsor: EventSponsorInput,
+  sponsorType: string,
+) => sponsor.type === sponsorType;
+
```
Comment (ojeytonwilliams) [inline client/src/modules/dashboard/Events/components/EventFormUtils.ts:229]:
```suggestion
```
Inlined above.

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
Nice one! The sponsor form is really smooth now.  I found a few places where I felt there was a little too much abstraction, but that was it - the code's solid.

File: client/src/modules/dashboard/Events/components/EventFormUtils.ts (hunk 1 above)
Comment (gikf) [reply client/src/modules/dashboard/Events/components/EventFormUtils.ts:178]: This is lovely, I didn't realize `.length` on its own is already doing enough for `filter`.

**Review by gikf — COMMENTED** [review]
Thanks for looking :+1:, suggestions are on-point :rocket:

File: client/src/modules/dashboard/Events/components/EventFormUtils.ts (hunk 1 above)
Comment (ojeytonwilliams) [reply client/src/modules/dashboard/Events/components/EventFormUtils.ts]: Yeah, it works because 0 is the only falsy number. Which is pretty neat for things like this.

**Review by ojeytonwilliams — APPROVED** [review]
Cheers @gikf.  This LGTM :+1:
